# -*- coding: utf-8 -*-
"""untitled6 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KyGcvPtfoAZemGHhZw-VXafrDdDu_rh3
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline
sns.set(color_codes = True)

df=pd.read_csv('/content/enhanced_zomato_dataset_clean.csv')
print(df.head())
print(df.tail())



df.shape

df.info

df.describe()

df.dtypes

duplicate_rows_df = df[df.duplicated()]
print("number of duplicate rows:", duplicate_rows_df.shape)
df.count()

df=df.drop_duplicates()
df.head()

df.count()

print(df.isnull().sum())

df=df.dropna()
df.count()

sns.boxplot(x=df['Avg_Price_Cuisine'])

def extract_outliers_from_boxplot(array):
  q1=np.quantile(array,0.25)
  q3=np.quantile(array,0.75)
  iqr=q3-q1
  med=np.median(array)
  lower_bound=q1-(1.5*iqr)
  upper_bound=q3+(1.5*iqr)
  outliers=array[(array<=lower_bound) | (array>=upper_bound)]
  format(outliers)
  return outliers
extract_outliers_from_boxplot(df['Avg_Price_Cuisine'])

sns.boxplot(x=df['Avg_Price_Restaurant'])

def extract_outliers_from_boxplot(array):
  q1=np.quantile(array,0.25)
  q3=np.quantile(array,0.75)
  iqr=q3-q1
  med=np.median(array)
  lower_bound=q1-(1.5*iqr)
  upper_bound=q3+(1.5*iqr)
  outliers=array[(array<=lower_bound) | (array>=upper_bound)]
  format(outliers)
  return outliers
extract_outliers_from_boxplot(df['Avg_Price_Restaurant'])

df.Average_Rating.value_counts().nlargest(20).plot(kind='bar')

cor=df.select_dtypes(include=np.number).corr()
cor

plt.figure(figsize=(10,10))
sns.heatmap(cor,annot=True)

plt.subplots()
plt.scatter(df['Avg_Price_Cuisine'],df['Avg_Price_Restaurant'])